// +build linux

package config

// Valid signal numbers for this platform 
const (
	SIGUSR1    = 10
	SIGUSR2    = 12
	SIGRTMIN   = 34
	SIGRTMIN1  = SIGRTMIN + 1
	SIGRTMIN2  = SIGRTMIN + 2
	SIGRTMIN3  = SIGRTMIN + 3
	SIGRTMIN4  = SIGRTMIN + 4
	SIGRTMIN5  = SIGRTMIN + 5
	SIGRTMIN6  = SIGRTMIN + 6
	SIGRTMIN7  = SIGRTMIN + 7
	SIGRTMIN8  = SIGRTMIN + 8
	SIGRTMIN9  = SIGRTMIN + 9
	SIGRTMIN10 = SIGRTMIN + 10
	SIGRTMIN11 = SIGRTMIN + 11
	SIGRTMIN12 = SIGRTMIN + 12
	SIGRTMIN13 = SIGRTMIN + 13
	SIGRTMIN14 = SIGRTMIN + 14
	SIGRTMIN15 = SIGRTMIN + 15
	SIGRTMAX14 = SIGRTMAX - 14
	SIGRTMAX13 = SIGRTMAX - 13
	SIGRTMAX12 = SIGRTMAX - 12
	SIGRTMAX11 = SIGRTMAX - 11
	SIGRTMAX10 = SIGRTMAX - 10
	SIGRTMAX9  = SIGRTMAX - 9
	SIGRTMAX8  = SIGRTMAX - 8
	SIGRTMAX7  = SIGRTMAX - 7
	SIGRTMAX6  = SIGRTMAX - 6
	SIGRTMAX5  = SIGRTMAX - 5
	SIGRTMAX4  = SIGRTMAX - 4
	SIGRTMAX3  = SIGRTMAX - 3
	SIGRTMAX2  = SIGRTMAX - 2
	SIGRTMAX1  = SIGRTMAX - 1
	SIGRTMAX   = 64
)

func validateSignal(sig int) error {
	switch {
	case SIGUSR1 == sig:
	case SIGUSR2 == sig:
	case SIGRTMIN <= sig && SIGRTMAX >= sig:
	default:
		return errSignal
	}
	return nil
}

var sigMap = map[string]int{
	"SIGUSR1":     SIGUSR1,
	"SIGUSR2":     SIGUSR2,
	"SIGRTMIN":    SIGRTMIN,
	"SIGRTMIN+1":  SIGRTMIN1,
	"SIGRTMIN+2":  SIGRTMIN2,
	"SIGRTMIN+3":  SIGRTMIN3,
	"SIGRTMIN+4":  SIGRTMIN4,
	"SIGRTMIN+5":  SIGRTMIN5,
	"SIGRTMIN+6":  SIGRTMIN6,
	"SIGRTMIN+7":  SIGRTMIN7,
	"SIGRTMIN+8":  SIGRTMIN8,
	"SIGRTMIN+9":  SIGRTMIN9,
	"SIGRTMIN+10": SIGRTMIN10,
	"SIGRTMIN+11": SIGRTMIN11,
	"SIGRTMIN+12": SIGRTMIN12,
	"SIGRTMIN+13": SIGRTMIN13,
	"SIGRTMIN+14": SIGRTMIN14,
	"SIGRTMIN+15": SIGRTMIN15,
	"SIGRTMAX-14": SIGRTMAX14,
	"SIGRTMAX-13": SIGRTMAX13,
	"SIGRTMAX-12": SIGRTMAX12,
	"SIGRTMAX-11": SIGRTMAX11,
	"SIGRTMAX-10": SIGRTMAX10,
	"SIGRTMAX-9":  SIGRTMAX9,
	"SIGRTMAX-8":  SIGRTMAX8,
	"SIGRTMAX-7":  SIGRTMAX7,
	"SIGRTMAX-6":  SIGRTMAX6,
	"SIGRTMAX-5":  SIGRTMAX5,
	"SIGRTMAX-4":  SIGRTMAX4,
	"SIGRTMAX-3":  SIGRTMAX3,
	"SIGRTMAX-2":  SIGRTMAX2,
	"SIGRTMAX-1":  SIGRTMAX1,
	"SIGRTMAX":    SIGRTMAX,
}

func convertSignal(sigName string) (int, error) {
	if v, ok := sigMap[sigName]; ok {
		return v, nil
	}
	return 0, errSignal
}
